-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           10.1.16-MariaDB - mariadb.org binary distribution
-- OS do Servidor:               Win32
-- HeidiSQL Versão:              9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Copiando estrutura do banco de dados para biblioteca
CREATE DATABASE IF NOT EXISTS `biblioteca` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `biblioteca`;

-- Copiando estrutura para tabela biblioteca.livro
CREATE TABLE IF NOT EXISTS `livro` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Título` char(50) NOT NULL DEFAULT '0',
  `Autor` char(50) NOT NULL DEFAULT '0',
  `Editora` char(50) DEFAULT '0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=116 DEFAULT CHARSET=latin1;

-- Copiando dados para a tabela biblioteca.livro: ~112 rows (aproximadamente)
/*!40000 ALTER TABLE `livro` DISABLE KEYS */;
INSERT INTO `livro` (`Id`, `Título`, `Autor`, `Editora`) VALUES
	(1, 'HALO - 1', 'ALEXANDRA ADORNETTO', 'AGIR'),
	(2, 'HADES - 2', 'ALEXANDRA ADORNETTO', 'AGIR'),
	(3, 'HEAVEN - 3', 'ALEXANDRA ADORNETTO', 'AGIR'),
	(4, 'O ALICIADOR', 'D. CARRISI', 'RECORD'),
	(5, 'ESTRELA DA NOITE - 5', 'ALYSON NOËL', 'INTRÍNSECA'),
	(6, 'CHAMA NEGRA - 4', ' ALYSON NOËL', 'INTRÍNSECA'),
	(7, 'TERRA DE SOMBRAS - 3', 'ALYSON NOËL', 'INTRÍNSECA'),
	(8, 'LUA AZUL - 2', 'ALYSON NOËL', 'INTRÍNSECA'),
	(9, 'INFINITO - 6', 'ALYSON NOËL', 'INTRÍNSECA'),
	(10, 'PARA SEMPRE - 1', 'ALYSON NOËL', 'INTRÍNSECA'),
	(11, 'OBSESSÃO', 'T. MOSS', 'FUNDAMENTO'),
	(12, 'COBIÇA', 'T. MOSS', 'FUNDAMENTO'),
	(13, 'A MENINA QUE ROUBAVA LIVROS', 'MARKUS ZUSAK', 'INTRÍNSECA'),
	(14, 'EU SOU O MENSAGEIRO', 'MARKUS ZUSAK', 'INTRÍNSECA'),
	(15, 'A GAROTA QUE EU QUERO', 'MARKUS ZUSAK', 'INTRÍNSECA'),
	(16, 'RADIANTE', 'ALYSON NOËL', 'INTRÍNSECA'),
	(17, 'SE EU FICAR', 'GAYLE FORMAN', 'NOVO CONCEITO'),
	(18, 'PARA ONDE ELA FOI', 'GAYLE FORMAN', 'NOVO CONCEITO'),
	(19, 'APENAS UM ANO', 'GAYLE FORMAN', 'NOVO CONCEITO'),
	(20, 'EU ESTIVE AQUI', 'GAYLE FORMAN', 'ARQUEIRO'),
	(21, 'O SEXTO HOMEM', 'DAVID BALDACCI', 'ARQUEIRO'),
	(22, 'TODA A VERDADE', 'DAVID BALDACCI', 'ARQUEIRO'),
	(23, 'MEMÓRIAS DE UM VENDEDOR DE MULHERES', 'GIORGIO FALETTI', 'INTRÍNSECA'),
	(24, 'EU MATO', 'GIORGIO FALETTI', 'INTRÍNSECA'),
	(25, 'A ÚLTIMA CARTA DE AMOR', 'JOJO MOYES', 'INTRÍNSECA'),
	(26, 'COMO EU ERA ANTES DE VOCÊ', 'JOJO MOYES', 'INTRÍNSECA'),
	(27, 'CIDADES DE PAPEL', 'JOHN GREEN', 'INTRÍNSECA'),
	(28, 'QUEM É VOCÊ ALASCA', 'JOHN GREEN', 'MARTINS FONTES'),
	(29, 'DESTRUA ESTE DIÁRIO', 'KERI SMITH', 'INTRÍNSECA'),
	(30, 'PERFEITOS', 'SCOTT WESTERFELD', 'GALERA'),
	(31, 'FEIOS', 'SCOTT WESTERFELD', 'GALERA'),
	(35, 'O GUIA DO MOCHILEIRO DAS GALÁXIAS - 1', 'DOUGLAS ADAMS', 'ARQUEIRO'),
	(36, 'O RESTAURANTE NO FIM DO MUNDO - 2', 'DOUGLAS ADAMS', 'ARQUEIRO'),
	(37, 'A VIDA, O UNIVERSO E TUDO MAIS - 3', 'DOUGLAS ADAMS', 'ARQUEIRO'),
	(38, 'ATÉ MAIS, E OBRIGADO PELOS PEIXES! - 4', 'DOUGLAS ADAMS', 'ARQUEIRO'),
	(39, 'PRATICAMENTE INOFENSIVA - 5', 'DOUGLAS ADAMS', 'ARQUEIRO'),
	(40, 'DIÁRIO DE UMA PAIXÃO', 'NICHOLAS SPARKS', 'NOVO CONCEITO'),
	(41, 'QUERIDO JOHN', 'NICHOLAS SPARKS', 'NOVO CONCEITO'),
	(42, 'AS CINCO PESSOAS QUE VOCÊ ENCONTRA NO CÉU', 'MITCH ALBOM', 'SEXTANTE'),
	(43, 'POR MAIS UM DIA', 'MITCH ALBOM', 'SEXTANTE'),
	(44, 'TENHA UM POUCO DE FÉ', 'MITCH ALBOM', 'SEXTANTE'),
	(45, 'A ÚLTIMA GRANDE LIÇÃO', 'MITCH ALBOM', 'SEXTANTE'),
	(46, 'O MONTE CINCO', 'PAULO COELHO', 'KLICK'),
	(47, 'O ALEPH', 'PAULO COELHO', 'SEXTANTE'),
	(48, 'O VENCEDOR ESTÁ SÓ', 'PAULO COELHO', 'AGIR'),
	(49, 'GOSTO DE VOCÊ ASSIM', 'FRANCESCO GUNGUI', 'FUNDAMENTO'),
	(50, 'O PREÇO DE UMA LIÇÃO', 'FREDERICO DEVITO & GUTTI MENDONÇA', 'NOVO CONCEITO'),
	(51, 'FILHA MÃE AVÓ E PUTA', 'GABRIELA LEITE', 'OBJETIVA'),
	(52, 'ESPUMAS FLUTUANTES', 'CASTRO ALVES', 'KLICK'),
	(53, 'CIDADE DOS OSSOS - 1', 'CASSANDRA CLARE', 'GALERA'),
	(54, 'CIDADE DAS CINZAS - 2', 'CASSANDRA CLARE', 'GALERA'),
	(55, 'CIDADE DE VIDRO - 3', 'CASSANDRA CLARE', 'GALERA'),
	(56, 'CIDADE DOS ANJOS CAÍDOS - 4', 'CASSANDRA CLARE', 'GALERA'),
	(57, 'CIDADE DAS ALMAS PERDIDAS - 5', 'CASSANDRA CLARE', 'GALERA'),
	(58, 'CIDADE DO FOGO CELESTIAL - 6', 'CASSANDRA CLARE', 'GALERA'),
	(59, 'A TEORIA DE TUDO', 'JANE HAWKING', 'ÚNICA'),
	(60, 'O GUARDIÃO DE MEMÓRIAS', 'KIM EDWARDS', 'SEXTANTE'),
	(61, 'O PACTO', 'JOE HILL', 'SEXTANTE'),
	(62, 'ÁGUA PARA ELEFANTES', 'SARA GRUEN', 'SEXTANTE'),
	(63, 'NA ILHA', 'TRACEY GARVIS GRAVES', 'INTRÍNSECA'),
	(64, 'O LADO BOM DA VIDA', 'MATTHEW QUICK', 'INTRÍNSECA'),
	(65, 'GUIA DE UMA CICLISTA EM KASHGAR', 'SUZANNE JOINSON', 'INTRÍNSECA'),
	(66, 'ORANGE IS THE NEW BLACK', 'PIPER KERMAN', 'INTRÍNSECA'),
	(67, 'DE REPENTE ACONTECE', 'SUSANE COLASANTI', 'NOVO CONCEITO'),
	(68, 'UMA VIDA SEM LIMITES', 'NICK VUJICIC', 'NOVO CONCEITO'),
	(69, 'NÃO SOU ESTE TIPO DE GAROTA', 'SIOBHAN VIVIAN', 'NOVO CONCEITO'),
	(70, 'MEU VIZINHO É UM PSICOPATA', 'MARTHA STOUT', 'SEXTANTE'),
	(71, 'A VERDADE SOBRE NÓS', 'AMANDA GRACE', 'INTRÍNSECA'),
	(72, 'O JOVEM SHERLOCK HOLMES - TEMPESTADE DE FOGO', 'ANDREW LANE', 'INTRÍNSECA'),
	(73, 'O MENINO DO PIJAMA LISTRADO', 'JOHN BOYNE', 'CIA DAS LETRAS'),
	(74, 'ÉPOCA DE MORANGOS', 'RAFAELLA VIEIRA', 'GUTENBERG'),
	(75, 'O PORTUGUÊS QUE NOS PARIU', 'ANGELA DUTRA DE MENEZES', 'RECORD'),
	(76, 'FAZENDO MEU FILME - A ESTRELA DE FANI - 1', 'PAULA PIMENTA', 'GUTENBERG'),
	(77, 'CARTAS DE AMOR AOS MORTOS', 'AVA DELLAIRA', 'SEGUINTE'),
	(78, 'PACIENTE PARTICULAR', 'P. D. JAMES', 'CIA DAS LETRAS'),
	(79, 'TEMPO FECHADO', 'KEN FOLLET', 'ROCCO'),
	(80, 'SCARPETTA', 'PATRICIA CORNWELL', 'PARALELA'),
	(81, 'DANÇA DA MORTE', 'DOUGLAS PRESTON & LINCOLN CHILD', 'RECORD'),
	(82, 'A OUTRA FACE', 'JOHN MACARTHUR', 'THOMAS NELSON BRASIL'),
	(83, 'A MANCHA DE SANGUE', 'ASA LARSSON', 'PLANETA'),
	(84, 'A MENINA QUE NÃO SABIA LER', 'JOHN HARDING', 'LEYA'),
	(85, 'A PASSAGEM', 'JUSTIN CRONIN', 'ARQUEIRO'),
	(86, 'AUTO DA COMPADECIDA', 'ARIANO SUASSUNA', 'AGIR'),
	(87, 'O CÓDIGO DA VINCI', 'DAN BROWN', 'SEXTANTE'),
	(88, 'DIÁRIO DE UM BANANA - FAÇA VOCÊ MESMO', 'JEFF KINNEY', 'V&R'),
	(89, 'DIÁRIO DE UM BANANA - 1', 'JEFF KINNEY', 'V&R'),
	(90, 'DIÁRIO DE UM BANANA - RODRICK É O CARA - 2', 'JEFF KINNEY', 'V&R'),
	(91, 'DIÁRIO DE UM BANANA - A GOTA D\'ÁGUA - 3', 'JEFF KINNEY', 'V&R'),
	(92, 'DIÁRIO DE UM BANANA - DIAS DE CÃO - 4', 'JEFF KINNEY', 'V&R'),
	(93, 'DIÁRIO DE UM BANANA - A VERDADE NUA E CRUA - 5', 'JEFF KINNEY', 'V&R'),
	(94, 'DIÁRIO DE UM BANANA - CASA DOS HORRORES - 6', 'JEFF KINNEY', 'V&R'),
	(95, 'DIÁRIO DE UM BANANA - SEGURANDO VELA - 7', 'JEFF KINNEY', 'V&R'),
	(96, 'DIÁRIO DE UM BANANA- VAI OU RACHA - 11', 'JEFF KINNEY', 'V&R'),
	(97, 'PONTO DE IMPACTO', 'DAN BROWN', 'SEXTANTE'),
	(98, 'O DIA DE CAÇA', 'JAMES PATTERSON', 'ARQUEIRO'),
	(99, 'EU, ALEX CROSS', 'JAMES PATTERSON', 'ARQUEIRO'),
	(100, 'PRIVATE', 'JAMES PATTERSON', 'ARQUEIRO'),
	(101, '4 DE JULHO', 'JAMES PATTERSON', 'ARQUEIRO'),
	(102, '5° CAVALEIRO', 'JAMES PATTERSON', 'ARQUEIRO'),
	(103, '6° ALVO', 'JAMES PATTERSON', 'ARQUEIRO'),
	(104, 'SEM DEIXAR RASTROS', 'HARLAN COBEN', 'ARQUEIRO'),
	(105, 'NÃO CONTE A NINGUÉM', 'HARLAN COBEN', 'ARQUEIRO'),
	(106, 'UM PASSO EM FALSO', 'HARLAN COBEN', 'ARQUEIRO'),
	(107, 'SEIS ANOS DEPOIS', 'HARLAN COBEN', 'ARQUEIRO'),
	(108, 'A TODA PROVA', 'HARLAN COBEN', 'ARQUEIRO'),
	(109, 'QUEBRA DE CONFIANÇA', 'HARLAN COBEN', 'ARQUEIRO'),
	(110, 'ALTA TENSÃO', 'HARLAN COBEN', 'ARQUEIRO'),
	(111, 'CILADA', 'HARLAN COBEN', 'SEXTANTE'),
	(112, 'CONFIE EM MIM', 'HARLAN COBEN', 'SEXTANTE'),
	(113, 'DESAPARECIDO PARA SEMPRE', 'HARLAN COBEN', 'SEXTANTE'),
	(114, 'A CIDADE DO SOL', 'KHALED HOSSEINI', 'NOVA FRONTEIRA'),
	(115, 'SONETOS PARA AMAR O AMOR', 'CAMÕES', 'L&PM');
/*!40000 ALTER TABLE `livro` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
